
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = b'3K&0\x10\xe9IL\xbb\xe5\xa1\xfe\x88\x0c,\x17'
    
_lr_action_items = {'TIMES':([1,2,5,11,12,13,14,15,],[-6,6,-7,-4,-5,6,6,-8,]),'DIVIDE':([1,2,5,11,12,13,14,15,],[-6,7,-7,-4,-5,7,7,-8,]),'NUM':([0,4,6,7,8,9,],[5,5,5,5,5,5,]),'RPAREN':([1,2,5,10,11,12,13,14,15,],[-6,-3,-7,15,-4,-5,-2,-1,-8,]),'PLUS':([1,2,3,5,10,11,12,13,14,15,],[-6,-3,9,-7,9,-4,-5,-2,-1,-8,]),'$end':([1,2,3,5,11,12,13,14,15,],[-6,-3,0,-7,-4,-5,-2,-1,-8,]),'MINUS':([1,2,3,5,10,11,12,13,14,15,],[-6,-3,8,-7,8,-4,-5,-2,-1,-8,]),'LPAREN':([0,4,6,7,8,9,],[4,4,4,4,4,4,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expr':([0,4,],[3,10,]),'factor':([0,4,6,7,8,9,],[1,1,11,12,1,1,]),'term':([0,4,8,9,],[2,2,13,14,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expr","S'",1,None,None,None),
  ('expr -> expr PLUS term','expr',3,'p_expr','/home/eyouyan/git/python-cookbook/simple_ply_parser.py',39),
  ('expr -> expr MINUS term','expr',3,'p_expr','/home/eyouyan/git/python-cookbook/simple_ply_parser.py',40),
  ('expr -> term','expr',1,'p_expr_term','/home/eyouyan/git/python-cookbook/simple_ply_parser.py',50),
  ('term -> term TIMES factor','term',3,'p_term','/home/eyouyan/git/python-cookbook/simple_ply_parser.py',56),
  ('term -> term DIVIDE factor','term',3,'p_term','/home/eyouyan/git/python-cookbook/simple_ply_parser.py',57),
  ('term -> factor','term',1,'p_term_factor','/home/eyouyan/git/python-cookbook/simple_ply_parser.py',66),
  ('factor -> NUM','factor',1,'p_factor','/home/eyouyan/git/python-cookbook/simple_ply_parser.py',72),
  ('factor -> LPAREN expr RPAREN','factor',3,'p_factor_group','/home/eyouyan/git/python-cookbook/simple_ply_parser.py',79),
]
